name: make test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dir
      run: ls -alF
    - name: hello
      run: echo "Hello World!"
    - name: cd src
      run: cd src
    - name: dir2
      run: ls -alF
    - name: make
      run: make
    - name: make test
      run: make test
