name: make test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 
      run: make
      working-directory: ./src
    - name: perl cmdline_test.pl
      run: perl cmdline_test.pl
      working-directory: ./test
    - name: perl oligotm_test.pl
      run: perl oligotm_test.pl
      working-directory: ./test
    - name: perl dpal_test.pl
      run: perl dpal_test.pl
      working-directory: ./test
    - name: perl thal_test.pl
      run: perl thal_test.pl
      working-directory: ./test
    - name: perl masker_test.pl
      run: perl masker_test.pl
      working-directory: ./test
    - name: perl p3test.pl
      run: perl p3test.pl
      working-directory: ./test


  build-macOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./src
    - name: perl cmdline_test.pl
      run: perl cmdline_test.pl
      working-directory: ./test
    - name: perl oligotm_test.pl
      run: perl oligotm_test.pl
      working-directory: ./test
    - name: perl dpal_test.pl
      run: perl dpal_test.pl
      working-directory: ./test
    - name: perl thal_test.pl
      run: perl thal_test.pl
      working-directory: ./test
    - name: perl masker_test.pl
      run: perl masker_test.pl
      working-directory: ./test
    - name: perl p3test.pl
      run: perl p3test.pl
      working-directory: ./test


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make TESTOPTS=--windows
      run: make TESTOPTS=--windows
      working-directory: ./src
    - name: perl cmdline_test.pl --windows
      run: perl cmdline_test.pl --windows
      working-directory: ./test
    - name: perl oligotm_test.pl --windows
      run: perl oligotm_test.pl --windows
      working-directory: ./test
    - name: perl dpal_test.pl --windows
      run: perl dpal_test.pl --windows
      working-directory: ./test
    - name: perl thal_test.pl --windows
      run: perl thal_test.pl --windows
      working-directory: ./test
    - name: perl p3test.pl --windows
      run: perl p3test.pl --windows
      working-directory: ./test

