name: make test macOS-latest

on:
  push:
    branches: [ master ]

jobs:
  build-macOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./src
    - name: perl cmdline_test.pl
      run: perl cmdline_test.pl
      working-directory: ./test
    - name: perl oligotm_test.pl
      run: perl oligotm_test.pl
      working-directory: ./test
    - name: perl dpal_test.pl
      run: perl dpal_test.pl
      working-directory: ./test
    - name: perl thal_test.pl
      run: perl thal_test.pl
      working-directory: ./test
    - name: perl masker_test.pl
      run: perl masker_test.pl
      working-directory: ./test
    - name: perl p3test.pl
      run: perl p3test.pl
      working-directory: ./test
    - name: mkdir results
      run: mkdir results
    - name: tar -zcvf results/build-macOS-src.tar.gz ./src
      run: tar -zcvf results/build-macOS-src.tar.gz ./src
    - name: tar -zcvf results/build-macOS-test.tar.gz ./test
      run: tar -zcvf results/build-macOS-test.tar.gz ./test
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: build-macOS-src.tar.gz
        path: results/build-macOS-src.tar.gz
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: build-macOS-test.tar.gz
        path: results/build-macOS-test.tar.gz
